// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "greet/internal/handler/user"
	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: user.GreetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sign/demo",
				Handler: SignDemoHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
	)
}
